addpath(genpath(pwd));

classes = {  '0.HC'; '1.EMCI'; '2.MCI'; '3.LMCI'; '4.AD';};
for index = 1:size(classes)
    path = ['./Data/'  char(classes(index, 1)) '/'];
    files = dir(path);
    for subject_index = 1:size(files, 1)
        if files(subject_index).isdir == 0
            cmd = ['load ' path files(subject_index).name];
            eval(cmd);
            [ strength, ...
              clustering_coef, ...
              local_efficiency, ...
              betweenness, ...
              eigenvector, ...
              subgraph, ...
              kcoreness, ...
              flow_efficiency, ...
              pagerank...
            ] = BCT_calculation(path, result);
        
        end
    end
        
end