tic;
clear;
addpath(genpath(pwd));

classes = {  '0.HC'; '1.EMCI'; '2.MCI'; '3.LMCI'; '4.AD';};
for index = 1:size(classes)
    path = ['./Data/Connectivity/'  char(classes(index, 1)) '/'];
    files = dir(path);
    subjects = zeros(24, 3241);
    subject_index = 1;
    for file_index = 1:size(files, 1)
        if files(file_index).isdir == 0
            load([path files(file_index).name]);
            [strength, ...
              clustering_coef, ...
              local_efficiency, ...
              betweenness, ...
              eigenvector, ...
              subgraph, ...
              kcoreness, ...
              flow_efficiency, ...
              pagerank...
            ] = BCT_calculation(result);
            features = [strength, ...
                          clustering_coef, ...
                          local_efficiency, ...
                          betweenness, ...
                          eigenvector, ...
                          subgraph, ...
                          kcoreness, ...
                          flow_efficiency, ...
                          pagerank...
                       ];
            type = char(classes(index, 1));
            if type(1) == '0'
                type = 1;
            elseif type(1) == '1'
                type = 2;
            elseif type(1) == '2'
                type = 3;
            elseif type(1) == '3'
                type = 4;
            elseif type(1) == '4'
                type = 5;
            end
            subject = [type, features];
            subjects(subject_index, :) = subject;
            subject_index = subject_index + 1;
        end
    end
    name = ['./Data/BCTs/' char(classes(index, 1)) '.mat'];
    save(name, 'subjects');      
end
toc;