function [   strength, ...
             clustering_coef, ...
             local_efficiency, ...
             betweenness, ...
             eigenvector, ...
             subgraph, ...
             kcoreness, ...
             flow_efficiency, ...
             pagerank...
] = Features_calculation(network)
%%
strength = strengths_und(network);
clustering_coef = clustering_coef_bu(network)';
local_efficiency = efficiency_bin(network, 1)';
betweenness = betweenness_bin(network);
eigenvector = eigenvector_centrality_und(network)';
subgraph = subgraph_centrality(network)';
kcoreness = kcoreness_centrality_bu(network);
flow_efficiency = flow_coef_bd(network);
pagerank = pagerank_centrality(network, 0.85)';
